### ISSUE TITLE
[Bug] Addition of income does not generate correct acknowledgement message

### ISSUE THREAD

**Issue by chinhan99** [AY2223S1-CS2113-W12-2/tp#128]
![image](https://user-images.githubusercontent.com/62207919/197564393-c7554cd2-f312-4f17-98df-f74fa3ec884e.png)

In this screenshot, the default monthly budget value is taken to be at default at $1000. When a new Income transaction is added with `add t/income c/salary a/2000 d/30092022 i/jan_salary`, the acknowledgement message shows a negative value, due to incorrect operation of the income values. Supposedly, the income should be incremented to the monthly budget.

**Comment by wcwy** [comment]
Spot on! The bug happens as when the total expense amount is calculated, a loop was used to iterate through the transaction list to sum up the amount. However, there was no check to ensure that the transaction type is an "expense", thus the amount of the "income" type transactions is also added to the total sum. 

This bug is fixed in PR #129.
