### ISSUE TITLE
[PE-D][Tester D] Can consider changing add command for ease of use

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-W12-2/tp#165]
![image.png](https://raw.githubusercontent.com/dhanish265/ped/main/files/ff9b58d6-4a3a-4bbc-af8d-0b9170ce2673.png)

instead of having the user write expense or income repeatedly for each add command, t/E or t/I can be used instead (since it can only refer to that)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dhanish265/ped#2

**Comment by chydarren** [comment]
Thank you for this feedback! One of our user stories required that the user would like similar features to be grouped under the same family of commands so that it is easy for him/her to remember which command perform which type of related function. In this scenario, adding an income or expense falls under the addition of a transaction into the list, which is why both are classified under the `Add` command instead of two separate commands on its own. 

Nonetheless, we are appreciative of this feedback.
