### ISSUE TITLE
As a careless user, I want to modify my spending or expenses in the application

### ISSUE THREAD

**Issue by chydarren** [AY2223S1-CS2113-W12-2/tp#27]
... so that I can rectify any false input

**Comment by wcwy** [comment]
User story is moved to Milestone v2.0 due to insufficient time. While the edit command is not implemented, a user can perform the editing of a transaction by deleting the transaction and adding it with the edited parameter(s) instead. 

Since the feature can be completed with add and delete, edit command is deemed closer to being an enhancement and thus the priority is lower to medium.

**Comment by chydarren** [comment]
Noted on the moving to Milestone V2.0, approved.
